### ISSUE TITLE
Question about pitree's inputs

### ISSUE THREAD

**Issue by adarsh1github1** [thu-media/Comyco#10]
I see that in the pitree implementation last_vmaf in an input. Is that last chunks vmaf? If yes, is that vmaf calculated on client side and how is that calculated?

**Comment by godka** [comment]
Sorry for the long delay. 

> Is that the last chunk's vmaf?

The short answer is yes.

> If yes, is that vmaf calculated on the client side and how is that calculated?

Nope. The vmaf score was calculated during the video transcoding process, and we stored the value on the server.
Thus, no additional computation will be affected on the client side, such as calculating VMAF or the last chunks' quality score -- the client can request the VMAF score from the server. For more information please check Section 5.2.
