### ISSUE TITLE
Questions about the training dataset and the testing dataset.

### ISSUE THREAD

**Issue by 1195917230** [thu-media/Comyco#12]
I noticed that the files used for the training dataset and the testing dataset are the same. Is this a mistake in the code?
TRAIN_TRACES = './cooked_test_traces/'
TEST_TRACES = './cooked_test_traces/'

**Comment by godka** [comment]
Hi,

Nice catch. It does a minor issue for the public repo.
Feel free to pull requests to resolve this issue.

Thank you so much.

Best,
Tianchi
