### ISSUE TITLE
Can't plot anything.

### ISSUE THREAD

**Issue by Wannabeperfect** [thu-media/Comyco#2]
Hello:
  I retry to run plot_results.py at the folder src, but it can not show anything. How can I fix it? Thanks~

**Comment by godka** [comment]
Details are plotted in './details/cdf.png'.
Please feel free to let me know if u have any questions.

**Comment by Wannabeperfect** [comment]
Yes. I know the result is plotted in './details/cdf.png'. However, after I run plot_results.py, the figure is empty.   But I've already fixed it. I modify your script.

**Comment by godka** [comment]
Glad to see this. Have a nice day.

**Comment by dixitabhanderi** [comment]
Hello, 
@Wannabeperfect & @godka what are the modifications made to get the results plotted using plot_results.py file? 
Thanks.
