### ISSUE TITLE
Some problems about instant solver implement for linux

### ISSUE THREAD

**Issue by YihuaZou** [thu-media/Comyco#6]
Thank you for your work.
https://github.com/thu-media/Comyco/blob/38cc0266b1c0a9f20e48a173d0157452cb411b85/cpp-linux/mpc.cpp#L162
I am very confused about this line of code. The constructor of the environment class requires a string argument, but this gives two vectors. If  replace the parameter with the file address, maybe this is correct. But what is the meaning of the previous line of code：
https://github.com/thu-media/Comyco/blob/38cc0266b1c0a9f20e48a173d0157452cb411b85/cpp-linux/mpc.cpp#L161

**Comment by godka** [comment]
Hi Yihua,

Point well taken. We have mistakenly uploaded our previous version of the RMPC code to the Comyco repo.

An easier solution is to change the line 162 to 'auto net_env = new Env('./path_to_test/')' instead.

Regarding the next question, maybe it's one of the easier ways to directly get the trace info and, print it.
You can revise the code as you wish. Welcome to pull the request if have already done the modification:).

Please feel free to let me know if you've any other questions.

Best,
Tianchi.
