### ISSUE TITLE
Help for instant solver

### ISSUE THREAD

**Issue by ma3252788** [thu-media/Comyco#7]
Hello, I ran into a problem while reproducing this code. Hope to communicate with you. I saw the description of the instant solver in the paper 4.2, but I don't know how this part is reflected in the code, and I haven't found it after searching for it for a long time. Can you help me?

**Comment by ma3252788** [comment]
In addition, I saw the mpc.cpp file in the cpp-linux directory, but I did not see other codes calling this file. What is the function of this file?

**Comment by godka** [comment]
Hi Ma,
The instant solver can be found at:

https://github.com/thu-media/Comyco/blob/master/cpp-win/abr/env.cpp

For more details please refer to this link (Chinese version):

https://www.jianshu.com/p/0c3d3993d26d

**Comment by ma3252788** [comment]
> Hi Ma,
> The instant solver can be found at:
> 
> https://github.com/thu-media/Comyco/blob/master/cpp-win/abr/env.cpp
> 
> For more details please refer to this link (Chinese version):
> 
> https://www.jianshu.com/p/0c3d3993d26d

Okay, got it. Thank you. You mean mpc.cpp is meaningless for comyco, right?

**Comment by godka** [comment]
> > Hi Ma,
> > The instant solver can be found at:
> > https://github.com/thu-media/Comyco/blob/master/cpp-win/abr/env.cpp
> > For more details please refer to this link (Chinese version):
> > https://www.jianshu.com/p/0c3d3993d26d
> 
> Okay, got it. Thank you. You mean mpc.cpp is meaningless for comyco, right?

Yep. It's just a cpp version of RobustMPC, reference only.

**Comment by ma3252788** [comment]
Okay, got it. Is the instant solver the function `void Environment::get_optimal(double last_video_vmaf)` in env.cpp?

**Comment by godka** [comment]
Yes

Tianchi Huang

**Comment by ma3252788** [comment]
So the reward model has two functions, one is to help the instant solver to obtain the expert strategy, and the other is to reward the actions of the Neural network?

**Comment by godka** [comment]
Sorry, I didn't catch that, or how about using Chinese to express your question?

**Comment by ma3252788** [comment]
> Sorry, I didn't catch that, or how about using Chinese to express your question?

尴尬了……其实我是想问，QoE(reward) model的作用是不是有两个，一个是帮助instant solver找出专家策略，另一个是一般的RL中reward的作用，给agent的action一个奖励？

**Comment by godka** [comment]
应该只有第一个作用，Comyco没有用RL技术。

PS：git上只讨论代码层面的问题，和论文相关的问题可以私下在邮件里解决。
